//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touhou.Extraction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Touhou.Extraction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\actor\ObjectCommon.nut
        ///data\actor\block\Steelframe_block0000.png
        ///data\actor\block\Steelframe_block0001.png
        ///data\actor\block\Steelframe_block0002.png
        ///data\actor\block\Steelframe_block0003.png
        ///data\actor\block\block.pat
        ///data\actor\block\clear-block_0000.png
        ///data\actor\block\clear_charactor.png
        ///data\actor\block\crack-block_0000.png
        ///data\actor\block\crack-block_0001.png
        ///data\actor\block\ice-floor_0000.png
        ///data\actor\block\nomal-block_0000.png
        ///data\actor\block\nomal-block_rotate0000.png
        ///data\ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fileslist {
            get {
                return ResourceManager.GetString("fileslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  &quot;app.conf&quot;,
        ///  &quot;data.cga&quot;,
        ///  &quot;data.cgb&quot;,
        ///  &quot;data\\bgm\\.index&quot;,
        ///  &quot;data\\bgm\\flandre1.ogg&quot;,
        ///  &quot;data\\bgm\\flandre1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\jyoon1.ogg&quot;,
        ///  &quot;data\\bgm\\jyoon1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\kanako1.ogg&quot;,
        ///  &quot;data\\bgm\\kanako1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\kogasa1.ogg&quot;,
        ///  &quot;data\\bgm\\kogasa1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\marisa1.ogg&quot;,
        ///  &quot;data\\bgm\\marisa1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\murasa1.ogg&quot;,
        ///  &quot;data\\bgm\\murasa1.ogg.ini&quot;,
        ///  &quot;data\\bgm\\niwatari1.ogg&quot;,
        ///  &quot;data\\bgm\\niwatari1.ogg.ini&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string th175 {
            get {
                return ResourceManager.GetString("th175", resourceCulture);
            }
        }
    }
}
